services:
  users_service:
    build: .
    command: sh -c "cd /app && air"
    depends_on:
      postgresdb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 9090:9090
    networks:
      - users-service-network
    volumes:
      - .:/app

  postgresdb:
    image: 'postgres:16'
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - users-service-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'ayousers', '-d', 'usersdb']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  users-service-network:
    driver: bridge

volumes:
  users-service_postgres_data: {}